# Form implementation generated from reading ui file 'ascii_transform_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(312, 187)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../MinePicture/ico/文档.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 150, 81, 24))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(70, 20, 71, 31))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 61, 31))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QLineEdit(parent=Form)
        self.line.setGeometry(QtCore.QRect(150, 20, 61, 31))
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QLineEdit(parent=Form)
        self.line_2.setGeometry(QtCore.QRect(150, 60, 61, 31))
        self.line_2.setObjectName("line_2")
        self.radio = QtWidgets.QRadioButton(parent=Form)
        self.radio.setGeometry(QtCore.QRect(90, 100, 141, 21))
        self.radio.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radio.setChecked(True)
        self.radio.setObjectName("radio")
        self.radio_2 = QtWidgets.QRadioButton(parent=Form)
        self.radio_2.setGeometry(QtCore.QRect(90, 120, 141, 21))
        self.radio_2.setObjectName("radio_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ASCII Code Transformer"))
        self.pushButton.setText(_translate("Form", "Transform"))
        self.label.setText(_translate("Form", "Character :"))
        self.label_2.setText(_translate("Form", "Code :"))
        self.radio.setText(_translate("Form", "Character to Code"))
        self.radio_2.setText(_translate("Form", "Code to Character"))
